services:
  prusa-camera:
    image: linuxserver/ffmpeg
    restart: always
    entrypoint: /bin/bash
    command: /upload.sh
    env_file:
      - .env
    devices:
      - /dev/video0:/dev/video0
    volumes:
      - ./upload.sh:/upload.sh
